### ISSUE TITLE
No Form showing at middle breakpoint

### ISSUE THREAD

**Issue by djjonbrown** [nelsW70/jenkins-for-da#1]
How is the user supposed to access the form?

<img width="874" alt="screen shot 2018-07-01 at 8 52 22 am" src="https://user-images.githubusercontent.com/8303925/42134568-26ad066c-7d0c-11e8-87a4-11c9f4aa85d2.png">

**Comment by nelsW70** [comment]
Magic.

They'll need to condense access to it because there isn't room in the
header at that size for all the inputs and a button. We could put a button
somewhere but that's up to you.

Could put both buttons in the header w/logo left and adjust the spacing in
the footer. Friends text left and social icons right.

Or allow for a larger page and put it below the hero logo.

Or put it in the footer with two rows of content.

**Comment by djjonbrown** [comment]
There will be a menu with sections in future. We should probably plan for that now. 

Here, let's move the Join Us button to the TopNav in this version- with no form.

**Comment by nelsW70** [comment]
How do you feel about this button/logo placement?

**Comment by djjonbrown** [comment]
Looks great
